name: WebdriverIO Test Suite

on:
  push:
    branches:
      - main
      - new-branch
  pull_request:
    branches:
      - main
      - new-branch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MOCHA_TIMEOUT: 180000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO tests
        run: npm run wdio
